modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="fly"
version="1.0.0"
displayName="fly"
description="Use /fly to activate/deactivate"
credits="Created by S4CBS"
displayURL="https://github.com/S4CBS/fly-1.16.5"
authors="S4CBS"

[[dependencies.fly]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




